print("My Name is shiva")
print("I'm %s years old." %'27')
print("I completed %s in %s year with %s percent."  % ('B.Sc','2018','75%'))
print("Currently I'm doing job in %s from last %s months" % ('BajajFinance','6.10'))
print("I got marriage in %s year" %'2016')
print("Almost %d years months completed" %6.2)
print("I have %d kids" %2.0)
print("Elder one is my daughter Her name is %s and her age is 8Y." %'Dharshitha')
print("Younger one is my son and his name is %s" %'Yeeyansh Kumar')